# This is a basic workflow to help you get started with Actions

# Reference:
# - https://github.com/ad-m/github-push-action

name: Generate and PR

on:
  pull_request:
    branches: [master]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Print tool versions
        run: |
          npm -v
          node -v

      - name: Checkout yaml for code generation
        uses: actions/checkout@v2

      - name: generate code
        run: |
          mkdir generated-sdk
          java -jar ./bin/utils/openapi-generator-cli.jar generate -i developer.yaml -g javascript -o generated-sdk
          sed -i -e 's/trulioo_sdk/trulioo-sdk/g; s/GIT_USER_ID/GIT-USER-ID/g; s/GIT_REPO_ID/GIT-REPO-ID/g;' generated-sdk/README.md
          sed -i -e 's/"license": "Unlicense"/"license": "Apache-2.0"/g; s/"name": "trulioo_sdk"/"name": "trulioo-sdk"/g; s/"description": "Trulioo_SDK"/"description": "Trulioo JavaScript SDK"/g;' generated-sdk/package.json

      - name: Save the artifact
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: generated-sdk

  pull_request:
    needs: generate
    runs-on: ubuntu-latest
    steps:
      - name: Download the default branch of remote repository
        uses: actions/checkout@v2
        with:
          repository: Trulioo/sdk-js
          path: current_code

      - name: Download the artifact to the correct path
        uses: actions/download-artifact@v2
        with:
          name: artifact
          path: new_code

      - name: code update
        run: |
          rsync -a --delete new_code/ current_code/javascript

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.LANGUAGE_REPO_TOKEN }}
          branch-suffix: timestamp
          path: current_code
          branch: auto-generated/cr
